name: Testing Portal using e2e
on:
  workflow_call:
    inputs:
      environmentTags:
        type: string
        default: ""
        required: false
      targetUrl:
        type: string
        default: "https://staging-portal.zksync.dev/"
        required: true
      network:
        type: string
        default: "Goerli"
        required: true
      publish_to_allure: #Here we define the variable that can be overwritten by caller workflow
        type: boolean
        description: "Publish test results to allure"
        default: true
        required: false

env:
  E2E_WALLET_SECRET_PK: ${{ secrets.E2E_WALLET_SECRET_PK }}
  E2E_WALLET_SALT_IV: ${{ secrets.E2E_WALLET_SALT_IV }}
  E2E_WALLET_PASSWORD_MM: ${{ secrets.E2E_WALLET_PASSWORD_MM }}

  E2E_WALLET_1_MAIN: ${{ vars.E2E_WALLET_1_MAIN }}
  E2E_WALLET_2_SECOND: ${{ vars.E2E_WALLET_2_SECOND }}
  E2E_WALLET_0_EMPTY: ${{ vars.E2E_WALLET_0_EMPTY }}

  E2E_WALLET_1_MAIN_PUB_KEY: ${{ vars.E2E_WALLET_1_MAIN_PUB_KEY }}
  E2E_WALLET_2_SECOND_PUB_KEY: ${{ vars.E2E_WALLET_2_SECOND_PUB_KEY }}
  E2E_WALLET_0_EMPTY_PUB_KEY: ${{ vars.E2E_WALLET_0_EMPTY_PUB_KEY }}

  E2E_WALLET_1_MAIN_SHORT_SIX: ${{ vars.E2E_WALLET_1_MAIN_SHORT_SIX }}
  E2E_WALLET_1_MAIN_SHORT_FOUR: ${{ vars.E2E_WALLET_1_MAIN_SHORT_FOUR }}
  E2E_WALLET_2_SECOND_SHORT_FOUR: ${{ vars.E2E_WALLET_2_SECOND_SHORT_FOUR }}
  E2E_WALLET_0_EMPTY_SHORT_FOUR: ${{ vars.E2E_WALLET_0_EMPTY_SHORT_FOUR }}

jobs:
  e2e:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 20
      matrix:
        command: ["xvfb-run --auto-servernum --server-args '-screen 0 1920x1080x24' npx cucumber-js --tags "]
        tags: ["@transactions and not @emptyWallet"]

    name: "${{ matrix.tags }}"

    container:
      image: mcr.microsoft.com/playwright:v1.35.1-focal
      options: --user root
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Create metamask extension folder
        run: |
          mkdir -p ./tests/e2e/src/support/extension
          chown -R root ./
          chmod 777 -R ./tests/e2e/src/support/extension

      - name: Install Dependencies
        run: |
          npm i --no-audit

      - name: Install Metamask extension
        run: |
          echo "cd to tests/e2e/ dir"
          cd tests/e2e/
          echo "Postinstall"
          npm run postinstall

      - name: Download allurectl
        run: |
          wget https://github.com/allure-framework/allurectl/releases/latest/download/allurectl_linux_386 -O ./allurectl

      - name: Change permission for allurectl
        run: |
          chmod +x ./allurectl

      - name: Launch tests
        id: launch
        env:
          CI: "true"
          TARGET_ENV: ${{ vars.TARGET_ENV }}
          DAPP_NETWORK: ${{ inputs.network }}
        run: |
          echo "Run tests"
          cd tests/e2e/
          ${{ matrix.command }}'${{ matrix.tags }} ${{ inputs.environmentTags }}'

      - name: Reset tags quotes
        if: always()
        run: |
          echo "MATRIX_TAG_WITHOUT_QUOTES=$(echo ${{ matrix.tags }} | sed -e 's/@//g' )" >> $GITHUB_ENV

      - if: failure()
        name: Save artifacts
        uses: actions/upload-artifact@v2
        with:
          name: portal_e2e_${{ github.run_number }}_artifacts
          path: tests/e2e/artifacts/*
