name: Deploy To Feature Branch
on:
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    outputs:
      dappUrl: ${{ steps.deploy.outputs.details_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci --force

      - name: Lint
        run: |
          npm run lint

      - name: Setup .env
        run: |
          echo "WALLET_CONNECT_PROJECT_ID=${{ secrets.WALLET_CONNECT_PROJECT_ID }}" > .env
          echo "ANKR_TOKEN=${{ secrets.ANKR_TOKEN }}" >> .env
          echo "SCREENING_API_URL=${{ secrets.SCREENING_API_URL }}" >> .env
          echo "DATAPLANE_URL=${{ secrets.DATAPLANE_URL }}" >> .env
          echo "RUDDER_KEY=${{ secrets.RUDDER_KEY }}" >> .env

      - name: Build
        run: |
          npm run generate

      - name: Deploy
        uses: matter-labs/action-hosting-deploy@main
        id: deploy
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_STAGING_ZKSYNC_DAPP_WALLET_V2 }}"
          projectId: staging-zksync-dapp-wallet-v2
          expires: 7d
